<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<div class="actions">
    <button <?php $block->getUiId(); ?>
            class="action-login action-primary">
        <span><?= $escaper->escapeHtml(__('Sign in')); ?></span>
    </button>
</div>
