<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Backend\Block\Page\RequireJs;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var RequireJs $block */
/** @var SecureHtmlRenderer $secureRenderer */

$scriptString = '
    var BASE_URL = \'' . /* @noEscape */ $block->getUrl('*') . '\';
    var FORM_KEY = \'' . /* @noEscape */ $block->getFormKey() . '\';
    var require = {
        \'baseUrl\': \'' . /* @noEscape */ $block->getViewFileUrl('/') . '\'
    };';

echo /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false);
