<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Backend\Block\Dashboard\Grid;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Escaper $escaper */
/** @var Grid $block */
/** @var SecureHtmlRenderer $secureRenderer */
$numColumns = count($block->getColumns());
?>
<?php if ($block->getCollection()): ?>
    <div class="dashboard-item-content">
        <?php if ($block->getCollection()->getSize() > 0): ?>
            <table class="admin__table-primary dashboard-data"
                   id="<?= $escaper->escapeHtmlAttr($block->getId()); ?>_table">
                <?php if ($block->getHeadersVisibility() || $block->getFilterVisibility()): ?>
                    <thead>
                        <?php if ($block->getHeadersVisibility()): ?>
                            <tr>
                                <?php foreach ($block->getColumns() as $_column): ?>
                                    <?= $_column->getHeaderHtml(); ?>
                                <?php endforeach; ?>
                            </tr>
                        <?php endif; ?>
                    </thead>
                <?php endif; ?>

                <?php if (!$block->getIsCollapsed()): ?>
                    <tbody>
                        <?php foreach ($block->getCollection() as $_index => $_item): ?>
                            <tr title="<?= $escaper->escapeHtmlAttr($block->getRowUrl($_item)); ?>">
                                <?php $i = 0; ?>

                                <?php foreach ($block->getColumns() as $_column): ?>
                                    <td class="<?= $escaper->escapeHtmlAttr($_column->getCssProperty()); ?> <?= /* @noEscape */ ++$i == $numColumns ? 'last' : '';?>">
                                        <?= /* @noEscape */ ($_html = $_column->getRowField($_item)) !== ''
                                            ? $_html
                                            : '&nbsp;'; ?>
                                    </td>
                                <?php endforeach; ?>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                <?php endif; ?>
            </table>
        <?php else: ?>
            <div class="<?= $escaper->escapeHtmlAttr($block->getEmptyTextClass()); ?>">
                <?= $escaper->escapeHtml($block->getEmptyText()); ?>
            </div>
        <?php endif; ?>
    </div>
    <?php if ($block->canDisplayContainer()): ?>
        <?php $scriptString = 'var deps = [];' . PHP_EOL; ?>

        <?php if ($block->getDependencyJsObject()): ?>
            <?php $scriptString .= 'deps.push(\'uiRegistry\');' . PHP_EOL; ?>
        <?php endif; ?>

        <?php if (strpos($block->getRowClickCallback(), 'order.') !== false): ?>
            <?php $scriptString .= 'deps.push(\'Magento_Sales/order/create/form\');' . PHP_EOL; ?>
        <?php endif; ?>

        <?php $scriptString .= 'deps.push(\'mage/adminhtml/grid\');' . PHP_EOL; ?>

        <?php $scriptString .= 'require(deps, function('
            . ($block->getDependencyJsObject() ? 'registry' : '')
            .'){'
            . PHP_EOL
            . '//TODO: getJsObjectName and getRowClickCallback has unexpected behavior. Should be removed'
            . PHP_EOL; ?>

        <?php if ($block->getDependencyJsObject()): ?>
            <?php $scriptString .= 'registry.get(\''
                . $escaper->escapeJs($block->getDependencyJsObject())
                . '\', function ('
                . $escaper->escapeJs($block->getDependencyJsObject())
                . ') {'
                . PHP_EOL; ?>
        <?php endif; ?>

        <?php $scriptString .= $escaper->escapeJs($block->getJsObjectName())
            . ' = new varienGrid(\''
            . $escaper->escapeJs($block->getId())
            . '\', \''
            . $escaper->escapeJs($block->getGridUrl())
            . '\', \''
            . $escaper->escapeJs($block->getVarNamePage())
            .'\', \''
            . $escaper->escapeJs($block->getVarNameSort())
            . '\', \''
            . $escaper->escapeJs($block->getVarNameDir())
            . '\', \''
            . $escaper->escapeJs($block->getVarNameFilter())
            . '\');'
            . PHP_EOL; ?>

        <?php $scriptString .= $escaper->escapeJs($block->getJsObjectName())
            .'.useAjax = \''
            . $escaper->escapeJs($block->getUseAjax())
            . '\';'
            . PHP_EOL; ?>

        <?php if ($block->getRowClickCallback()): ?>
            <?php $scriptString .= $escaper->escapeJs($block->getJsObjectName())
                . '.rowClickCallback = '
                . /* @noEscape */ $block->getRowClickCallback()
                . ';'
                . PHP_EOL; ?>
        <?php endif; ?>

        <?php if ($block->getCheckboxCheckCallback()): ?>
            <?php $scriptString .= $escaper->escapeJs($block->getJsObjectName())
                . '.checkboxCheckCallback = '
                . /* @noEscape */ $block->getCheckboxCheckCallback()
                . ';'
                . PHP_EOL; ?>
        <?php endif; ?>

        <?php if ($block->getRowInitCallback()): ?>
            <?php $scriptString .= $escaper->escapeJs($block->getJsObjectName())
                . '.initRowCallback = '
                . /* @noEscape */ $block->getRowInitCallback()
                . ';'
                . PHP_EOL
                . $escaper->escapeJs($block->getJsObjectName())
                . '.rows.each(function(row){'
                . /* @noEscape */ $block->getRowInitCallback()
                . '('
                . $escaper->escapeJs($block->getJsObjectName())
                . ', row)});'
                . PHP_EOL; ?>
        <?php endif; ?>

        <?php if ($block->getMassactionBlock()->isAvailable()): ?>
            <?php $scriptString .= /* @noEscape */ $block->getMassactionBlock()->getJavaScript(); ?>
        <?php endif; ?>

        <?php if ($block->getDependencyJsObject()): ?>
            <?php $scriptString .=  '});' . PHP_EOL; ?>
        <?php endif; ?>

        <?php $scriptString .= '});' . PHP_EOL; ?>

        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
    <?php endif; ?>
<?php endif; ?>
